services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: test_integracao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_VICENTE_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - net-vicente

  app:
    image: vicentesimao/atomated-test2:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test_integracao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_VICENTE_PASSWORD}
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - postgres
    networks:
      - net-vicente
networks:
  net-vicente: 
    driver: bridge
